### ISSUE TITLE
make used tasks a bit more configurable

### ISSUE THREAD

**Issue by berndbischl** [ja-thomas/OMLbots#10]
we need to be able to easiliy switch between 2 things

a) study_14 (reaslistic)

b) something EXTRMELY small. low obs, few data sets, just holdout, etc

**Comment by berndbischl** [comment]
actraully also have a "set" of verly fast learners, for testing.

and the realistic set.

fast are rpart, linear model, etc.

**Comment by DanielKuehn87** [comment]
Why do we actually need this? Since all the data is stored on the server, can't we just get data from there? Imo, no need to run stuff locally.

**Comment by ja-thomas** [comment]
Both done.

We now have `simple.lrn.par.set` and `lrn.par.set` as well as `sampleSimpleTask()`
