### ISSUE TITLE
Literature

### ISSUE THREAD

**Issue by PhilippPro** [ja-thomas/OMLbots#27]
I did a literature search (also for my other paper). 
Here are the papers divided by topic, maybe you can add yours to the specific topic, if you know some more.

 Tuning in general: 
-  Tuning with Iterated F-Racing: Automatic model selection for high-dimensional survival analysis
-  (iterated) F-Racing: F-Race and iterated F-Race: An overview, Mauro Birattari, Zhi Yuan, Prasanna Balaprakash, and Thomas Stutzle
-  AutoML: Efficient and Robust Automated Machine Learning, Feurer et. al
-  mlrMBO: A Modular Framework for Model-Based Optimization of Expensive Black-Box Functions, Bischl et al
-  mlrMBO: Faster Model-Based Optimization through Resource-Aware Scheduling Strategies, Richter et al
-  Hyperopt: a Python library for model selection and hyperparameter optimization (Pythons analogon to MBO)
-  Sequential MBO: Sequential Model-Based Optimization for General Algorithm Configuration, Hutter et al
-  Auto-WEKA:  combined selection and hyperparameter optimization of classification algorithms, Thornton et al
-  Practical Bayesian Optimization of Machine Learning Algorithms

 
 Meta-Learning: 
 

- Multi-Task Bayesian Optimization, Kwersky et. al
-  To tune or not to tune: recommending when to adjust SVM hyper-parameters via metalearning
-  Collaborative hyperparameter tuning, Bardenet et. al
-  Hyperparameter Optimization Machines, Wistuba et. al
-  Using meta-learning to initialize bayesian optimization of hyperparameters, Feurer et al
-  Scalable Hyperparameter Optimization with Products of Gaussian Process Experts, Schilling et. al
-  Sequential Model-Free Hyperparameter Tuning, Wistuba et. al
-  Two-Stage Transfer Surrogate Model for Automatic Hyperparameter Optimization, Wistuba et. al
-  Learning hyperparameter optimization initializations, Wistuba et. al

 Hyperparameter Importance:

-  An Efficient Approach for Assessing Hyperparameter Importance
- Identifying key algorithm parameters and instance features using forward selection
- Analysing differences between algorithm configurations through ablation
- Efficient Parameter Importance Analysis via Ablation with Surrogates
- Hyper-parameter Tuning of a Decision Tree Induction Algorithm

 Surrogate Models:
-  Surrogate benchmarks for hyperparameter optimization, Eggensperger et. al (RF is best)
-  Efficient Benchmarking  of  Hyperparameter  Optimizers  via Surrogates

 Time Prediction:
-  Prediction of Classifier Training Time Including Parameter Optimization, Reif et. al

 Time AND Performance:
-  Fast Bayesian Optimization of Machine Learning Hyperparameters on Large Datasets, Klein et al

**Comment by ja-thomas** [comment]
You forgot the most important paper :(

https://arxiv.org/abs/1703.03373

**Comment by berndbischl** [comment]
For irace:

Tuning with Iterated F-Racing: Automatic model selection for high-dimensional survival analysis..

**Comment by berndbischl** [comment]
> Practical Bayesian Optimization of Machine Learning Algorithms

why is this under meta learning?

**Comment by berndbischl** [comment]
> Surrogate Models:

das sieht mir mehr section "benchmarks" aus

**Comment by berndbischl** [comment]
und genereller kommentar:

das hier wird JETZT SCHON eine riesensammlung zu allem was zu HPO existiert? das sollte garantiert hier nicht rein. sondern in mendeley!

**Comment by berndbischl** [comment]
(ich finde es ja seeeehr sinnvoll so eine liste zu sammeln, aber dann auch richtig)

**Comment by PhilippPro** [comment]
Kann man in mendeley nach Topics ordnen? Im Moment sehe ich nur eine Riesenanzahl an Papers in der CompStat Gruppe, die dort ungeordnet rumliegen...

**Comment by berndbischl** [comment]
> Kann man in mendeley nach Topics ordnen?

das hoffe ich doch sehr. hast du einen bezahlten account den wir dir geschenkt haben?

**Comment by PhilippPro** [comment]
Ok, ja geht, muss mich erst ein bisschen mit der Oberfläche dort zurecht finden.

**Comment by DanielKuehn87** [comment]
In der mendeley compstatLMU-Gruppe gibt es den Ordner: "Make defaults great again" :) Könntest die Paper ja da einfach mal reinwerfen. Man kann tags vergeben und dann per tag:"my_tag" suchen.

**Comment by PhilippPro** [comment]
Done, bis auf die allgemeinen Tuning Paper, dafür gibts ja schon genug andere Ordner/Dokumente in Mendeley. Hab jetzt mal Unterordner erstellt für die einzelnen Themen. (Wie funktioniert die Tag Vergabe?)

**Comment by DanielKuehn87** [comment]
Ok, cool. Vielen Dank.
