### ISSUE TITLE
runTime not downloadable for some runs

### ISSUE THREAD

**Issue by PhilippPro** [ja-thomas/OMLbots#37]
Für bestimmte runs geht das nicht:
```
> getRunTime(1886569)
Error in function (type, msg, asError = TRUE)  : Could not resolve host: �����
Zusätzlich: Warnmeldung:
In strsplit(msg, "\n") : Eingabe-Zeichenkette 1 ungültig in dieser locale
   run.id run.time sci.mark
1 1886569       NA       NA
```

Wenn wir noch ein bisschen warten (https://github.com/openml/OpenML/issues/426) wird das ganze über listOMLRunEvaluations verfügbar sein, dann brauchen wir diesen lästigen Umweg nicht mehr und es geht schneller.

**Comment by DanielKuehn87** [comment]
Wie viele sinds denn etwa? Ich werd mir das hier mal genauer anschauen: https://github.com/ja-thomas/OMLbots/issues/34 Damit kann man das Problem ggf. auch lösen.
