### ISSUE TITLE
Rpart & svm fails?

### ISSUE THREAD

**Issue by DanielKuehn87** [ja-thomas/OMLbots#39]
https://www.openml.org/u/2702/flows
https://www.openml.org/search?q=uploader_id%3A2702&type=flow&sort=runs&order=desc

Looks like we almost have no uploads for the SVM and rpart. I have a limit of 3.4 GB RAM and 2 hours runtime on Azure per run... but this should be enough at least for the smaller datasets. Not sure, what the issue is...

**Comment by PhilippPro** [comment]
I don't know what openml.org is showing but that is not true. The table in R shows following: 

```
mlr.classif.featureless      mlr.classif.glmnet        mlr.classif.kknn      mlr.classif.ranger       mlr.classif.rpart 
                    500                  100512                   91284                   65547                   92259 
        mlr.classif.svm     mlr.classif.xgboost 
                  70743                   72172 
```

**Comment by PhilippPro** [comment]
The Azuremachine is giving a big boost, we nearly have 1 000 000 results now. Not bad. Maybe the issue is valid for your runs on the azure machine...

**Comment by DanielKuehn87** [comment]
Hm ok, that's weird. Insbesondere bei rpart gibts ja nen ziemlichen Unterschied zwischen unseren Daten und dem openml-Dashboard... 
Wenn ich mir die aktuellen Runs anschaue wird auch recht viel für SVM/rpart geladen. Ist also ggf. echt ein Problem mit dem Dashboard.
